"""remove response_schema and ensure communication_style exists

Revision ID: 6bf58f431e75
Revises: 002
Create Date: 2026-02-04 22:59:53.063320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf58f431e75'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('communication_style', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'communication_style')
    # ### end Alembic commands ###
